#!/usr/bin/env python3
"""Export the sim's geometry to real .obj/.mtl model files.

The game builds its ring procedurally at runtime, which is great for shipping
source but means the repo contains no actual 3D model files.  This writes them
out properly, so the project ships with real, inspectable assets that open in
Blender / MeshLab / any 3D viewer, and that the game itself loads through the
same OBJ path a Sketchfab download would use.

    python3 tools/export_models.py

Writes into assets/models/:
    boxing_ring.obj / .mtl    the full ring (canvas, skirt, posts, ropes)
    boxer.obj / .mtl          a fighter in guard stance
"""
from __future__ import annotations

import os
import sys
from collections import OrderedDict

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

from boxing_sim.engine.mesh import Mesh                      # noqa: E402
from boxing_sim.engine import math3d as m3                   # noqa: E402


def _material_name(rgb) -> str:
    return "mat_%02x%02x%02x" % (int(rgb[0]), int(rgb[1]), int(rgb[2]))


def write_obj(mesh: Mesh, path: str, name: str = "model") -> tuple[int, int]:
    """Write `mesh` as .obj + .mtl, grouping faces by colour into materials.

    Returns (vertex_count, face_count).
    """
    obj_path = path
    mtl_path = os.path.splitext(path)[0] + ".mtl"
    os.makedirs(os.path.dirname(os.path.abspath(obj_path)), exist_ok=True)

    # group faces by their flat colour -> one material each
    groups: "OrderedDict[str, list]" = OrderedDict()
    colours: dict = {}
    for i, col in enumerate(mesh.colors):
        key = _material_name(col)
        groups.setdefault(key, []).append(i)
        colours[key] = col

    # per-face normals, so the exported model shades correctly everywhere
    v = mesh.verts[mesh.faces]
    n = np.cross(v[:, 1] - v[:, 0], v[:, 2] - v[:, 0])
    ln = np.linalg.norm(n, axis=1, keepdims=True)
    ln[ln < 1e-12] = 1.0
    n = n / ln

    with open(mtl_path, "w") as fh:
        fh.write(f"# {name} materials - generated by tools/export_models.py\n")
        for key, col in colours.items():
            r, g, b = (float(c) / 255.0 for c in col)
            fh.write(f"\nnewmtl {key}\n")
            fh.write(f"Kd {r:.4f} {g:.4f} {b:.4f}\n")
            fh.write(f"Ka {r*0.3:.4f} {g*0.3:.4f} {b*0.3:.4f}\n")
            fh.write("Ks 0.08 0.08 0.08\nNs 12.0\nd 1.0\nillum 2\n")

    with open(obj_path, "w") as fh:
        fh.write(f"# {name} - generated by tools/export_models.py\n")
        fh.write(f"# {len(mesh.verts)} vertices, {len(mesh.faces)} triangles\n")
        fh.write(f"mtllib {os.path.basename(mtl_path)}\n")
        fh.write(f"o {name}\n")
        for p in mesh.verts:
            fh.write(f"v {p[0]:.5f} {p[1]:.5f} {p[2]:.5f}\n")
        for d in n:
            fh.write(f"vn {d[0]:.5f} {d[1]:.5f} {d[2]:.5f}\n")
        for key, idxs in groups.items():
            fh.write(f"\nusemtl {key}\n")
            for i in idxs:
                a, b, c = (int(x) + 1 for x in mesh.faces[i])
                nn = i + 1
                fh.write(f"f {a}//{nn} {b}//{nn} {c}//{nn}\n")
    return len(mesh.verts), len(mesh.faces)


def build_ring() -> Mesh:
    """The complete ring, exactly as the game builds it."""
    from boxing_sim.game import arena as A
    parts = [A._canvas(), A._centre_logo()]
    r = A.RING_HALF
    parts += [
        A._post_pad(-r, -r, A.C_POST_RED),
        A._post_pad(r, -r, A.C_POST_BLUE),
        A._post_pad(r, r, A.C_POST_RED),
        A._post_pad(-r, r, A.C_POST_BLUE),
    ]
    parts += list(A._ropes().values())
    return Mesh.combine(parts, "boxing_ring")


def build_boxer() -> Mesh:
    """A fighter posed in guard stance, baked into a single mesh."""
    from boxing_sim.game.fighter import Fighter, FighterStats

    class _FlatArena:
        def clamp_to_ring(self, pos, radius=0.34):
            return pos, False

    stats = FighterStats(name="Boxer")
    f = Fighter(stats, m3.vec3(0, 0, 0), 0.0, True)
    o = Fighter(stats, m3.vec3(0, 0, 3.0), np.pi, False)
    # settle the rig into a clean guard pose
    for _ in range(30):
        f.update(1 / 60.0, o, _FlatArena(), (0.0, 0.0), True, False)

    me = f.meshes
    M = f._matrices
    parts = [
        me.hips.transform(M["hips"]),
        me.abdomen.transform(M["abdomen"]),
        me.chest.transform(M["chest"]),
        me.neck.transform(M["neck"]),
        me.head.transform(M["head"]),
    ]
    for hand in ("lead", "rear"):
        parts.append(me.upper_arm.transform(M[f"upper_{hand}"]))
        parts.append(me.forearm.transform(M[f"fore_{hand}"]))
        parts.append(me.glove.transform(M[f"glove_{hand}"]))
    for leg in ("lead", "rear"):
        parts.append(me.thigh.transform(M[f"thigh_{leg}"]))
        parts.append(me.shin.transform(M[f"shin_{leg}"]))
        parts.append(me.foot.transform(M[f"foot_{leg}"]))
    return Mesh.combine(parts, "boxer")


def main() -> int:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "assets", "models")

    for name, mesh in (("boxing_ring", build_ring()), ("boxer", build_boxer())):
        path = os.path.join(out, f"{name}.obj")
        nv, nf = write_obj(mesh, path, name)
        lo, hi = mesh.bounds()
        size = np.round(hi - lo, 2)
        print(f"{name + '.obj':20s} {nv:6d} verts  {nf:6d} tris   "
              f"size {size[0]:.2f} x {size[1]:.2f} x {size[2]:.2f} m")
    print(f"\nwritten to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
